# Generated by Django 4.1.1 on 2022-10-02 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WallpapersDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mainimage', models.ImageField(upload_to='images/')),
                ('favourite', models.BooleanField(default=False)),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='Wallpapers.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('wallpapers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallpapers', to='Wallpapers.wallpapersdetail')),
            ],
        ),
    ]
